"""teams state and nullable city columns

Revision ID: 8710345d53dc
Revises: 9cda593c8509
Create Date: 2026-07-12 21:36:36.739847

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8710345d53dc"
down_revision: str | Sequence[str] | None = "9cda593c8509"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("teams", sa.Column("state", sa.String(length=2), nullable=True))
    op.alter_column("teams", "city", existing_type=sa.VARCHAR(length=100), nullable=True)
    op.alter_column("venues", "city", existing_type=sa.VARCHAR(length=100), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("venues", "city", existing_type=sa.VARCHAR(length=100), nullable=False)
    op.alter_column("teams", "city", existing_type=sa.VARCHAR(length=100), nullable=False)
    op.drop_column("teams", "state")
    # ### end Alembic commands ###
