"""initial core schema

Revision ID: 9cda593c8509
Revises:
Create Date: 2026-07-12 21:04:45.859286

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9cda593c8509"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "seasons",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("year", sa.SmallInteger(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("year"),
    )
    op.create_table(
        "venues",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("altitude_meters", sa.Numeric(precision=6, scale=1), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("official_name", sa.String(length=150), nullable=False),
        sa.Column("short_name", sa.String(length=50), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("founded_year", sa.SmallInteger(), nullable=True),
        sa.Column("home_venue_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["home_venue_id"],
            ["venues.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_teams_home_venue_id"), "teams", ["home_venue_id"], unique=False)
    op.create_table(
        "matches",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("season_id", sa.BigInteger(), nullable=False),
        sa.Column("matchday", sa.SmallInteger(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("home_team_id", sa.BigInteger(), nullable=False),
        sa.Column("away_team_id", sa.BigInteger(), nullable=False),
        sa.Column("venue_id", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("result_type", sa.String(length=20), nullable=False),
        sa.Column("leg", sa.SmallInteger(), nullable=False),
        sa.Column("replay_of_match_id", sa.BigInteger(), nullable=True),
        sa.Column("home_score", sa.SmallInteger(), nullable=True),
        sa.Column("away_score", sa.SmallInteger(), nullable=True),
        sa.CheckConstraint(
            "result_type IN ('played', 'awarded_home', 'awarded_away', 'annulled')",
            name="ck_matches_result_type_valid",
        ),
        sa.CheckConstraint(
            "status IN ('scheduled', 'finished', 'postponed', 'cancelled')",
            name="ck_matches_status_valid",
        ),
        sa.CheckConstraint("home_team_id <> away_team_id", name="ck_matches_home_away_distinct"),
        sa.ForeignKeyConstraint(
            ["away_team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["replay_of_match_id"],
            ["matches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["seasons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["venues.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "season_id",
            "matchday",
            "home_team_id",
            "away_team_id",
            "leg",
            name="uq_matches_season_matchday_teams_leg",
        ),
    )
    op.create_index(op.f("ix_matches_away_team_id"), "matches", ["away_team_id"], unique=False)
    op.create_index(op.f("ix_matches_home_team_id"), "matches", ["home_team_id"], unique=False)
    op.create_index(
        op.f("ix_matches_replay_of_match_id"), "matches", ["replay_of_match_id"], unique=False
    )
    op.create_index(op.f("ix_matches_season_id"), "matches", ["season_id"], unique=False)
    op.create_index(op.f("ix_matches_venue_id"), "matches", ["venue_id"], unique=False)
    op.create_table(
        "season_teams",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("season_id", sa.BigInteger(), nullable=False),
        sa.Column("team_id", sa.BigInteger(), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=30), nullable=True),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["seasons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("season_id", "team_id", name="uq_season_teams_season_team"),
    )
    op.create_index(op.f("ix_season_teams_season_id"), "season_teams", ["season_id"], unique=False)
    op.create_index(op.f("ix_season_teams_team_id"), "season_teams", ["team_id"], unique=False)
    op.create_table(
        "team_external_ids",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("team_id", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("external_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source", "external_id", name="uq_team_external_ids_source_external_id"
        ),
        sa.UniqueConstraint("team_id", "source", name="uq_team_external_ids_team_source"),
    )
    op.create_index(
        op.f("ix_team_external_ids_team_id"), "team_external_ids", ["team_id"], unique=False
    )
    op.create_table(
        "match_external_ids",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("match_id", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("external_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("match_id", "source", name="uq_match_external_ids_match_source"),
        sa.UniqueConstraint(
            "source", "external_id", name="uq_match_external_ids_source_external_id"
        ),
    )
    op.create_index(
        op.f("ix_match_external_ids_match_id"), "match_external_ids", ["match_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_match_external_ids_match_id"), table_name="match_external_ids")
    op.drop_table("match_external_ids")
    op.drop_index(op.f("ix_team_external_ids_team_id"), table_name="team_external_ids")
    op.drop_table("team_external_ids")
    op.drop_index(op.f("ix_season_teams_team_id"), table_name="season_teams")
    op.drop_index(op.f("ix_season_teams_season_id"), table_name="season_teams")
    op.drop_table("season_teams")
    op.drop_index(op.f("ix_matches_venue_id"), table_name="matches")
    op.drop_index(op.f("ix_matches_season_id"), table_name="matches")
    op.drop_index(op.f("ix_matches_replay_of_match_id"), table_name="matches")
    op.drop_index(op.f("ix_matches_home_team_id"), table_name="matches")
    op.drop_index(op.f("ix_matches_away_team_id"), table_name="matches")
    op.drop_table("matches")
    op.drop_index(op.f("ix_teams_home_venue_id"), table_name="teams")
    op.drop_table("teams")
    op.drop_table("venues")
    op.drop_table("seasons")
    # ### end Alembic commands ###
