"""add team_season_stats_raw table

Revision ID: e4ee33db31c0
Revises: 8710345d53dc
Create Date: 2026-07-13 15:04:58.539501

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e4ee33db31c0"
down_revision: str | Sequence[str] | None = "8710345d53dc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team_season_stats_raw",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("team_id", sa.BigInteger(), nullable=False),
        sa.Column("season_id", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("raw_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["seasons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "team_id", "season_id", "source", name="uq_team_season_stats_raw_team_season_source"
        ),
    )
    op.create_index(
        op.f("ix_team_season_stats_raw_season_id"),
        "team_season_stats_raw",
        ["season_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_team_season_stats_raw_team_id"), "team_season_stats_raw", ["team_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_team_season_stats_raw_team_id"), table_name="team_season_stats_raw")
    op.drop_index(op.f("ix_team_season_stats_raw_season_id"), table_name="team_season_stats_raw")
    op.drop_table("team_season_stats_raw")
    # ### end Alembic commands ###
